### Games include pre and post season

In [229]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, GRU, LSTM
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor

from sklearn.linear_model import LinearRegression

In [106]:
df = pd.read_csv('./data/player_game_data.csv')

In [107]:
df.drop(columns = ['MIN'], inplace = True)

In [108]:
df.head()

,GAME_DATE_EST,GAME_ID,TEAM_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,PLAYER_NAME,SEASON,FGM,FGA,FG_PCT,...,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,SECONDS,FTSY_PTS
0,2021-05-26,42000102,1610612755,1610612755,1610612764,Anthony Tolliver,2020,0.0,0.0,0.000,...,45.0,95.0,0.402,0.633,0.091,22.0,40.0,1,104,0.0
1,2021-05-26,42000102,1610612755,1610612755,1610612764,Ben Simmons,2020,11.0,15.0,0.733,...,45.0,95.0,0.402,0.633,0.091,22.0,40.0,1,1714,43.0
2,2021-05-26,42000102,1610612755,1610612755,1610612764,Danny Green,2020,2.0,3.0,0.667,...,45.0,95.0,0.402,0.633,0.091,22.0,40.0,1,1304,12.0
3,2021-05-26,42000102,1610612755,1610612755,1610612764,Dwight Howard,2020,1.0,4.0,0.250,...,45.0,95.0,0.402,0.633,0.091,22.0,40.0,1,957,10.5
4,2021-05-26,42000102,1610612755,1610612755,1610612764,Furkan Korkmaz,2020,4.0,6.0,0.667,...,45.0,95.0,0.402,0.633,0.091,22.0,40.0,1,942,12.0

In [109]:
df.columns

Index(['GAME_DATE_EST', 'GAME_ID', 'TEAM_ID', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'PLAYER_NAME', 'SEASON', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TNO', 'PF', 'PTS', 'PLUS_MINUS',
       'PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away', 'HOME_TEAM_WINS', 'SECONDS', 'FTSY_PTS'],
      dtype='object')

In [152]:
df['GAME_DATE_EST'] = pd.to_datetime(df['GAME_DATE_EST'])

In [153]:
players = df[['PLAYER_NAME', 'SEASON', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TNO', 'PF', 'PTS', 'PLUS_MINUS', 'SECONDS', 'FTSY_PTS']]

In [154]:
players.fillna(0, inplace = True)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4317: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [171]:
play_season = players.groupby(['PLAYER_NAME', 'SEASON'], as_index= False)

In [172]:
play_season.mean()

,PLAYER_NAME,SEASON,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,...,REB,AST,STL,BLK,TNO,PF,PTS,PLUS_MINUS,SECONDS,FTSY_PTS
0,AJ Hammons,2016,0.653846,1.461538,0.171615,0.096154,0.230769,0.073712,0.173077,0.384615,...,1.153846,0.134615,0.019231,0.307692,0.269231,0.653846,1.576923,0.038462,283.634615,2.298077
1,AJ Hammons,2017,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Aaron Brooks,2015,2.411111,6.011111,0.318578,0.855556,2.433333,0.257644,0.688889,0.922222,...,1.322222,2.233333,0.411111,0.122222,1.077778,1.666667,6.366667,-0.022222,841.233333,7.194444
3,Aaron Brooks,2016,1.436782,3.643678,0.256851,0.563218,1.563218,0.209759,0.436782,0.540230,...,0.850575,1.494253,0.298851,0.103448,0.793103,1.160920,3.873563,-0.448276,651.632184,4.666667
4,Aaron Brooks,2017,0.352273,0.897727,0.129193,0.125000,0.409091,0.075750,0.113636,0.170455,...,0.193182,0.284091,0.068182,0.000000,0.136364,0.352273,0.943182,-0.886364,145.420455,0.960227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3673,Zhou Qi,2017,0.195652,0.826087,0.094913,0.086957,0.521739,0.043478,0.173913,0.260870,...,0.608696,0.043478,0.043478,0.391304,0.260870,0.434783,0.652174,-1.413043,189.543478,1.217391
3674,Zhou Qi,2018,0.200000,0.200000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,-0.400000,11.400000,0.400000
3675,Zion Williamson,2019,7.656250,12.781250,0.542250,0.218750,0.562500,0.125000,4.250000,6.562500,...,5.500000,1.843750,0.687500,0.281250,2.093750,1.656250,19.781250,2.843750,1456.593750,20.453125
3676,Zion Williamson,2020,9.958333,16.527778,0.607681,0.138889,0.555556,0.118056,5.763889,8.444444,...,7.194444,3.263889,1.013889,0.597222,2.652778,2.152778,25.819444,0.402778,1950.597222,29.229167
3677,Zylan Cheatham,2019,0.812500,1.125000,0.252938,0.000000,0.125000,0.000000,0.312500,0.500000,...,1.375000,0.187500,0.062500,0.125000,0.375000,0.875000,1.937500,-1.500000,315.000000,3.093750

In [212]:
curry = df.loc[df['PLAYER_NAME'] == 'Stephen Curry']

In [213]:
#curry_2016 = df.loc[(df['PLAYER_NAME'] == 'Stephen Curry') & (df['SEASON'] == 2016)]

In [214]:
#curry_2016 = curry_2016[['PLAYER_NAME', 'SEASON', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TNO', 'PF', 'PTS', 'PLUS_MINUS', 'SECONDS', 'FTSY_PTS']]

In [215]:
curry.set_index('GAME_DATE_EST', inplace = True)

In [216]:
curry.head()

,GAME_ID,TEAM_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,PLAYER_NAME,SEASON,FGM,FGA,FG_PCT,FG3M,...,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,SECONDS,FTSY_PTS
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2021-05-21,52000211,1610612744,1610612744,1610612763,Stephen Curry,2020,13.0,28.0,0.464,6.0,...,48.0,117.0,0.408,0.846,0.429,22.0,47.0,0,2843,34.5
2021-05-19,52000121,1610612744,1610612747,1610612744,Stephen Curry,2020,12.0,23.0,0.522,6.0,...,49.0,100.0,0.446,0.733,0.441,19.0,46.0,1,2437,30.5
2021-05-16,22001070,1610612744,1610612744,1610612763,Stephen Curry,2020,16.0,36.0,0.444,9.0,...,46.0,101.0,0.435,0.789,0.240,25.0,39.0,1,2397,42.5
2021-05-14,22001059,1610612744,1610612744,1610612740,Stephen Curry,2020,NaN,NaN,NaN,NaN,...,46.0,122.0,0.465,0.679,0.407,21.0,51.0,1,0,NaN
2021-05-11,22001039,1610612744,1610612744,1610612756,Stephen Curry,2020,7.0,22.0,0.318,1.0,...,40.0,116.0,0.519,0.900,0.432,26.0,36.0,1,2191,17.0

In [199]:
X_train.head()

,GAME_ID,TEAM_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,PLAYER_NAME,SEASON,FGM,FGA,FG_PCT,FG3M,...,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,SECONDS
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2015-10-05,11500009,1610612744,1610612744,1610612761,Stephen Curry,2015,5.0,7.0,0.714,3.0,...,29.0,37.0,87.0,0.376,0.826,0.250,15.0,48.0,1,1167
2015-10-08,11500026,1610612744,1610612757,1610612744,Stephen Curry,2015,6.0,14.0,0.429,6.0,...,25.0,48.0,101.0,0.383,0.794,0.375,20.0,38.0,1,1547
2015-10-13,11500056,1610612744,1610612744,1610612743,Stephen Curry,2015,5.0,13.0,0.385,1.0,...,23.0,43.0,114.0,0.495,0.600,0.429,29.0,48.0,0,1586
2015-10-15,11500063,1610612744,1610612744,1610612745,Stephen Curry,2015,6.0,7.0,0.857,1.0,...,31.0,43.0,101.0,0.365,0.828,0.233,24.0,55.0,1,1002
2015-10-17,11500073,1610612744,1610612747,1610612744,Stephen Curry,2015,7.0,13.0,0.538,5.0,...,18.0,36.0,70.0,0.387,0.684,0.450,14.0,37.0,1,1344

In [200]:
y_train

GAME_DATE_EST
2015-10-05    14.0
2015-10-08    33.5
2015-10-13    13.5
2015-10-15    30.0
2015-10-17    19.0
              ...
2019-03-27    37.5
2019-03-29    37.5
2019-03-31    38.0
2019-04-02    25.5
2019-04-04    16.5
Name: FTSY_PTS, Length: 352, dtype: float64

In [217]:
curry.dropna(inplace =True)

<ipython-input-217-137760249dc0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  curry.dropna(inplace =True)

In [218]:
curry.loc[curry['SECONDS']== 0]

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, HOME_TEAM_ID, VISITOR_TEAM_ID, PLAYER_NAME, SEASON, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TNO, PF, PTS, PLUS_MINUS, PTS_home, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, PTS_away, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away, HOME_TEAM_WINS, SECONDS, FTSY_PTS]
Index: []

[0 rows x 40 columns]

In [219]:
curry.sort_index(inplace = True)

<ipython-input-219-f9361c9f5863>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  curry.sort_index(inplace = True)

In [231]:
X= curry.drop(columns = ['FTSY_PTS', 'PLAYER_NAME'])
y= curry['FTSY_PTS']

In [232]:
X.head()

,GAME_ID,TEAM_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,FGM,FGA,FG_PCT,FG3M,FG3A,...,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,SECONDS
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2015-10-05,11500009,1610612744,1610612744,1610612761,2015,5.0,7.0,0.714,3.0,5.0,...,29.0,37.0,87.0,0.376,0.826,0.250,15.0,48.0,1,1167
2015-10-08,11500026,1610612744,1610612757,1610612744,2015,6.0,14.0,0.429,6.0,11.0,...,25.0,48.0,101.0,0.383,0.794,0.375,20.0,38.0,1,1547
2015-10-13,11500056,1610612744,1610612744,1610612743,2015,5.0,13.0,0.385,1.0,8.0,...,23.0,43.0,114.0,0.495,0.600,0.429,29.0,48.0,0,1586
2015-10-15,11500063,1610612744,1610612744,1610612745,2015,6.0,7.0,0.857,1.0,1.0,...,31.0,43.0,101.0,0.365,0.828,0.233,24.0,55.0,1,1002
2015-10-17,11500073,1610612744,1610612747,1610612744,2015,7.0,13.0,0.538,5.0,10.0,...,18.0,36.0,70.0,0.387,0.684,0.450,14.0,37.0,1,1344

In [233]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= .25, shuffle= False)

In [234]:
lr= LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [236]:
lr.predict(X_train)

array([14. , 33.5, 13.5, 30. , 19. , 41. , 46.5, 35. , 66.5, 36.5, 34. ,
       49. , 21.5, 23.5, 36.5, 48. , 26. , 38.5, 45. , 29. , 27.5, 34.5,
       47. , 34. , 30.5, 41.5, 41.5, 25. , 39. , 39. , 29.5, 30.5, 39.5,
       28.5, 28.5, 44. , 10. , 32. , 23. , 33.5, 50.5, 26. , 44.5, 26.5,
       40.5, 45. , 42.5, 59. , 44.5, 30.5, 25. , 14. , 50. , 34. , 42.5,
       41.5, 31.5, 30.5, 50. , 41.5, 60. , 47. , 32. , 14. , 51.5, 24. ,
       33. , 34. , 35.5, 36. , 44. , 17. , 33.5, 37.5, 48. , 29. , 37.5,
       30. , 26. , 49.5, 34.5, 38.5, 23. , 40.5, 52. , 31. ,  3.5, 41. ,
       38.5, 32.5, 27.5, 25.5, 13.5, 41. , 40.5, 39. ,  9. , 27. , 15.5,
       38. , 27. , 18.5, 12. , 11.5, 25.5, 23.5, 28. , 19.5, 41.5, 31. ,
       21. , 22. , 24.5, 22.5, 28.5, 28. , 47.5, 29. , 38. , 38. , 37.5,
       26. , 17.5, 33. , 43.5, 30.5, 41. , 20.5, 28.5, 28.5, 32.5, 34. ,
       26. , 15.5, 34.5, 31.5, 18. , 23. , 30. , 22.5, 30. , 17.5, 34.5,
       19.5, 19.5, 31.5, 40. , 32. , 32.5, 30.5, 29.5, 33. , 24.5, 30. ,
       27. , 28.5, 51. , 55. , 38.5, 45.5, 17. , 18.5, 41.5,  7.5, 22.5,
       46.5, 29.5, 16. , 25. , 25.5, 35. , 26.5, 27. , 21.5, 28.5, 36.5,
       35. , 22. , 32.5, 52. , 31.5, 36.5, 38.5, 29.5, 49. , 29.5, 54.5,
       31. , 23. , 29. , 25. , 39. , 45. , 30.5, 30. , 19. , 39.5, 40.5,
       45.5, 30.5, 34. , 42. , 42.5, 40. , 24. , 44. , 11. , 19. , 55. ,
       20.5, 23. , 33. , 37.5, 37. , 36.5, 27. , 35. , 43. , 34.5, 31.5,
       15. , 34. , 32.5, 14.5, 36.5, 48.5, 25. , 40. , 25. , 26.5, 35. ,
       34.5, 41.5, 42.5, 39. , 33.5, 48.5, 38.5, 36.5, 32. , 33. , 14. ,
       37.5, 41.5, 54.5, 11.5, 25. , 26. , 26.5, 30. , 29. , 31.5, 18. ,
       60. , 32. , 22.5, 21.5, 30.5, 42. ,  1. , 30.5, 31. , 24. , 16. ,
       39. , 33. , 19.5, 33.5, 22. , 33. , 36. , 44. , 36.5, 34. , 12. ,
       44. , 28. , 20. , 27.5, 24. , 43.5, 35. , 28. , 38. , 50.5, 27. ,
       30.5, 39.5, 42.5, 34.5, 22.5,  9. , 22.5, 30. , 51.5, 25. , 47. ,
        6.5, 44. , 19.5, 34.5, 19.5, 42. , 13.5, 28.5, 34. , 42. , 28. ,
       36. , 29. , 35. , 52.5, 32. , 39.5, 33. , 27. , 35.5, 22.5, 34.5,
       36. ,  8. , 31.5, 27.5, 25. , 34. , 27. , 42.5, 36.5, 20. , 21. ,
       26. , 28. , 22. , 12. , 28. , 26.5, 29.5, 34. , 38.5, 18.5])

In [238]:
lr.score(X_test, y_test)

1.0

In [223]:
ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train.drop(columns= ['GAME_ID','TEAM_ID','HOME_TEAM_ID','VISITOR_TEAM_ID','PLAYER_NAME','SEASON', 'HOME_TEAM_WINS']))
X_test_sc = ss.transform(X_test.drop(columns= ['GAME_ID','TEAM_ID','HOME_TEAM_ID','VISITOR_TEAM_ID','PLAYER_NAME','SEASON', 'HOME_TEAM_WINS']))

In [ ]:
ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train, feature_)
X_test_sc = ss.transform(X_test.drop(columns= ['GAME_ID','TEAM_ID','HOME_TEAM_ID','VISITOR_TEAM_ID','PLAYER_NAME','SEASON', 'HOME_TEAM_WINS']))

In [ ]:
feature_names_in_

In [227]:
train_seq = TimeseriesGenerator(X_train_sc, y_train, length=5, batch_size=64)
test_seq = TimeseriesGenerator(X_test_sc, y_test, length=5, batch_size=64)

In [225]:
train_seq[0]

(array([[[-1.25355238, -2.38430509,  1.98491538, ..., -1.74750541,
           0.71307526, -2.61510605],
         [-0.93548685, -0.93853538, -0.4387634 , ..., -0.91884176,
          -0.96474888, -1.40985909],
         [-1.25355238, -1.14507391, -0.81294538, ...,  0.57275282,
           0.71307526, -1.28616269],
         [-0.93548685, -2.38430509,  3.20100683, ..., -0.25591083,
           1.88755217, -3.13843696],
         [-0.61742132, -1.14507391,  0.48818743, ..., -1.91323814,
          -1.1325313 , -2.0537147 ]],

        [[-0.93548685, -0.93853538, -0.4387634 , ..., -0.91884176,
          -0.96474888, -1.40985909],
         [-1.25355238, -1.14507391, -0.81294538, ...,  0.57275282,
           0.71307526, -1.28616269],
         [-0.93548685, -2.38430509,  3.20100683, ..., -0.25591083,
           1.88755217, -3.13843696],
         [-0.61742132, -1.14507391,  0.48818743, ..., -1.91323814,
          -1.1325313 , -2.0537147 ],
         [ 0.01870974, -0.93853538,  1.38112172, ...,  0.90421828,
           2.223117  , -0.86749796]],

        [[-1.25355238, -1.14507391, -0.81294538, ...,  0.57275282,
           0.71307526, -1.28616269],
         [-0.93548685, -2.38430509,  3.20100683, ..., -0.25591083,
           1.88755217, -3.13843696],
         [-0.61742132, -1.14507391,  0.48818743, ..., -1.91323814,
          -1.1325313 , -2.0537147 ],
         [ 0.01870974, -0.93853538,  1.38112172, ...,  0.90421828,
           2.223117  , -0.86749796],
         [ 1.60903738,  1.53992698,  0.48818743, ..., -0.75310903,
          -1.80366096,  0.4614454 ]],

        ...,

        [[ 1.60903738,  1.12684992,  0.87087356, ..., -0.0901781 ,
          -1.97144337,  0.85473652],
         [ 0.97290632,  1.33338845, -0.00505246, ..., -0.5873763 ,
           0.37751043,  0.75958544],
         [-0.93548685,  0.3006958 , -1.53579695, ...,  1.06995101,
           0.88085768,  0.2077092 ],
         [ 1.60903738,  1.12684992,  0.87087356, ..., -0.25591083,
          -0.29361923,  0.78813076],
         [-1.57161791, -1.35161244, -1.25516046, ..., -0.75310903,
          -0.29361923, -0.31879342]],

        [[ 0.97290632,  1.33338845, -0.00505246, ..., -0.5873763 ,
           0.37751043,  0.75958544],
         [-0.93548685,  0.3006958 , -1.53579695, ...,  1.06995101,
           0.88085768,  0.2077092 ],
         [ 1.60903738,  1.12684992,  0.87087356, ..., -0.25591083,
          -0.29361923,  0.78813076],
         [-1.57161791, -1.35161244, -1.25516046, ..., -0.75310903,
          -0.29361923, -0.31879342],
         [ 1.29097185,  0.92031139,  0.71779911, ..., -0.91884176,
          -0.79696647, -0.71525623]],

        [[-0.93548685,  0.3006958 , -1.53579695, ...,  1.06995101,
           0.88085768,  0.2077092 ],
         [ 1.60903738,  1.12684992,  0.87087356, ..., -0.25591083,
          -0.29361923,  0.78813076],
         [-1.57161791, -1.35161244, -1.25516046, ..., -0.75310903,
          -0.29361923, -0.31879342],
         [ 1.29097185,  0.92031139,  0.71779911, ..., -0.91884176,
          -0.79696647, -0.71525623],
         [ 0.97290632,  1.12684992,  0.16503026, ...,  0.57275282,
           0.54529285,  0.34092071]]]),
 array([41. , 46.5, 35. , 66.5, 36.5, 34. , 49. , 21.5, 23.5, 36.5, 48. ,
        26. , 38.5, 45. , 29. , 27.5, 34.5, 47. , 34. , 30.5, 41.5, 41.5,
        25. , 39. , 39. , 29.5, 30.5, 39.5, 28.5, 28.5, 44. , 10. , 32. ,
        23. , 33.5, 50.5, 26. , 44.5, 26.5, 40.5, 45. , 42.5, 59. , 44.5,
        30.5, 25. , 14. , 50. , 34. , 42.5, 41.5, 31.5, 30.5, 50. , 41.5,
        60. , 47. , 32. , 14. , 51.5, 24. , 33. , 34. , 35.5]))

In [196]:
X_train.shape

(352, 39)

In [226]:
model = Sequential()

#add rnn layer
model.add(GRU(64, input_shape=(5,32), return_sequences=True))
model.add(GRU(16, return_sequences=False))
          
model.add(Dense(16, activation= 'relu'))
model.add(Dropout(.1))
model.add(Dense(8, activation= 'relu'))
model.add(Dropout(.2))
model.add(Dense(1))

model.compile(optimizer='adam', loss= 'mse', metrics= ['mae'])

history=model.fit(train_seq, epochs=30, validation_data= test_seq, verbose=1)

Epoch 1/30
6/6 [==============================] - 19s 1s/step - loss: 1125.2570 - mae: 31.8161 - val_loss: 1107.5117 - val_mae: 31.4658
Epoch 2/30
6/6 [==============================] - 0s 77ms/step - loss: 1113.0181 - mae: 31.6218 - val_loss: 1091.7037 - val_mae: 31.2210
Epoch 3/30
6/6 [==============================] - 0s 70ms/step - loss: 1097.4496 - mae: 31.3782 - val_loss: 1070.9926 - val_mae: 30.8944
Epoch 4/30
6/6 [==============================] - 1s 145ms/step - loss: 1076.9138 - mae: 31.0461 - val_loss: 1042.3774 - val_mae: 30.4382
Epoch 5/30
6/6 [==============================] - 0s 68ms/step - loss: 1048.6876 - mae: 30.5719 - val_loss: 1002.3681 - val_mae: 29.7899
Epoch 6/30
6/6 [==============================] - 0s 76ms/step - loss: 1007.7737 - mae: 29.9193 - val_loss: 948.4072 - val_mae: 28.8895
Epoch 7/30
6/6 [==============================] - 0s 79ms/step - loss: 951.2378 - mae: 28.9691 - val_loss: 878.0963 - val_mae: 27.6769
Epoch 8/30
6/6 [==============================] - 0s 65ms/step - loss: 876.8464 - mae: 27.6631 - val_loss: 797.7680 - val_mae: 26.2140
Epoch 9/30
6/6 [==============================] - 0s 69ms/step - loss: 790.5286 - mae: 25.9909 - val_loss: 718.2239 - val_mae: 24.6395
Epoch 10/30
6/6 [==============================] - 0s 70ms/step - loss: 704.8515 - mae: 24.3088 - val_loss: 646.1033 - val_mae: 23.1113
Epoch 11/30
6/6 [==============================] - 1s 143ms/step - loss: 621.8062 - mae: 22.5875 - val_loss: 578.0340 - val_mae: 21.6346
Epoch 12/30
6/6 [==============================] - 1s 131ms/step - loss: 562.3474 - mae: 21.2314 - val_loss: 512.9390 - val_mae: 20.1706
Epoch 13/30
6/6 [==============================] - 0s 87ms/step - loss: 491.5217 - mae: 19.4988 - val_loss: 451.1090 - val_mae: 18.6860
Epoch 14/30
6/6 [==============================] - 0s 81ms/step - loss: 455.7304 - mae: 18.4663 - val_loss: 393.6826 - val_mae: 17.1987
Epoch 15/30
6/6 [==============================] - 0s 66ms/step - loss: 416.9707 - mae: 17.2007 - val_loss: 339.9054 - val_mae: 15.7533
Epoch 16/30
6/6 [==============================] - 0s 71ms/step - loss: 339.2050 - mae: 15.5946 - val_loss: 291.2675 - val_mae: 14.4040
Epoch 17/30
6/6 [==============================] - 0s 84ms/step - loss: 300.6660 - mae: 14.2068 - val_loss: 246.2670 - val_mae: 13.0144
Epoch 18/30
6/6 [==============================] - 0s 75ms/step - loss: 273.9172 - mae: 13.4926 - val_loss: 209.4173 - val_mae: 11.8357
Epoch 19/30
6/6 [==============================] - 0s 68ms/step - loss: 244.0068 - mae: 12.6699 - val_loss: 180.2523 - val_mae: 10.8219
Epoch 20/30
6/6 [==============================] - 0s 75ms/step - loss: 210.1476 - mae: 11.5716 - val_loss: 158.7016 - val_mae: 10.0947
Epoch 21/30
6/6 [==============================] - 0s 80ms/step - loss: 192.7108 - mae: 10.6411 - val_loss: 143.1586 - val_mae: 9.5973
Epoch 22/30
6/6 [==============================] - 0s 71ms/step - loss: 208.0496 - mae: 11.4308 - val_loss: 133.1909 - val_mae: 9.2568
Epoch 23/30
6/6 [==============================] - 0s 68ms/step - loss: 193.7589 - mae: 11.2355 - val_loss: 128.2063 - val_mae: 9.0617
Epoch 24/30
6/6 [==============================] - 1s 157ms/step - loss: 195.0862 - mae: 10.8689 - val_loss: 125.1545 - val_mae: 8.9396
Epoch 25/30
6/6 [==============================] - 1s 103ms/step - loss: 160.9712 - mae: 10.0741 - val_loss: 123.3408 - val_mae: 8.8638
Epoch 26/30
6/6 [==============================] - 0s 77ms/step - loss: 166.6019 - mae: 10.2146 - val_loss: 122.1378 - val_mae: 8.8161
Epoch 27/30
6/6 [==============================] - 0s 89ms/step - loss: 181.0679 - mae: 10.6525 - val_loss: 121.7622 - val_mae: 8.7999
Epoch 28/30
6/6 [==============================] - 0s 87ms/step - loss: 179.4274 - mae: 10.7023 - val_loss: 122.1889 - val_mae: 8.8182
Epoch 29/30
6/6 [==============================] - 1s 156ms/step - loss: 176.0023 - mae: 10.4932 - val_loss: 122.1391 - val_mae: 8.8161
Epoch 30/30
6/6 [==============================] - 0s 82ms/step - loss: 183.3553 - mae: 11.0751 - val_loss: 122.6203 - val_mae: 8.8358

In [228]:
model.predict(train_seq)

array([[29.634014],
       [29.63548 ],
       [29.663954],
       [29.668447],
       [29.671085],
       [29.67096 ],
       [29.668308],
       [29.672102],
       [29.674156],
       [29.664589],
       [29.6461  ],
       [29.652445],
       [29.624632],
       [29.656435],
       [29.660135],
       [29.669165],
       [29.671362],
       [29.668213],
       [29.669062],
       [29.657999],
       [29.67096 ],
       [29.67359 ],
       [29.670103],
       [29.651297],
       [29.63535 ],
       [29.658304],
       [29.65986 ],
       [29.632528],
       [29.65193 ],
       [29.665195],
       [29.627687],
       [29.609835],
       [29.518173],
       [29.620821],
       [29.660013],
       [29.673882],
       [29.676306],
       [29.675383],
       [29.665201],
       [29.668144],
       [29.670944],
       [29.668812],
       [29.665888],
       [29.657347],
       [29.658136],
       [29.661106],
       [29.669298],
       [29.663319],
       [29.672482],
       [29.672533],
       [29.672386],
       [29.675005],
       [29.675003],
       [29.667288],
       [29.669685],
       [29.6682  ],
       [29.673014],
       [29.625319],
       [29.64958 ],
       [29.67026 ],
       [29.673506],
       [29.673346],
       [29.67449 ],
       [29.675146],
       [29.67481 ],
       [29.67238 ],
       [29.669893],
       [29.669668],
       [29.668198],
       [29.66899 ],
       [29.66835 ],
       [29.661484],
       [29.661371],
       [29.658895],
       [29.6668  ],
       [29.665083],
       [29.660683],
       [29.670431],
       [29.67504 ],
       [29.675457],
       [29.669237],
       [29.659435],
       [29.654068],
       [29.669527],
       [29.676407],
       [29.674734],
       [29.677397],
       [29.669212],
       [29.66635 ],
       [29.667301],
       [29.659908],
       [29.66549 ],
       [29.652666],
       [29.574648],
       [29.534313],
       [29.624598],
       [29.65259 ],
       [29.662436],
       [29.669785],
       [29.644567],
       [29.64864 ],
       [29.644636],
       [29.64643 ],
       [29.653833],
       [29.660618],
       [29.65749 ],
       [29.666384],
       [29.670128],
       [29.66241 ],
       [29.666983],
       [29.659351],
       [29.659126],
       [29.663038],
       [29.671648],
       [29.674824],
       [29.67661 ],
       [29.675066],
       [29.672308],
       [29.657919],
       [29.659212],
       [29.672127],
       [29.673506],
       [29.675331],
       [29.675976],
       [29.676435],
       [29.669067],
       [29.667677],
       [29.665041],
       [29.673943],
       [29.674608],
       [29.664078],
       [29.645128],
       [29.6238  ],
       [29.65913 ],
       [29.652746],
       [29.661457],
       [29.669863],
       [29.671011],
       [29.665693],
       [29.668411],
       [29.660465],
       [29.664394],
       [29.668653],
       [29.673626],
       [29.674812],
       [29.671   ],
       [29.67004 ],
       [29.662374],
       [29.66245 ],
       [29.672766],
       [29.673306],
       [29.668386],
       [29.64643 ],
       [29.627129],
       [29.660559],
       [29.669481],
       [29.674019],
       [29.67403 ],
       [29.673368],
       [29.671406],
       [29.673155],
       [29.658094],
       [29.673527],
       [29.675568],
       [29.66485 ],
       [29.660498],
       [29.656456],
       [29.666136],
       [29.661577],
       [29.654358],
       [29.622414],
       [29.648813],
       [29.655588],
       [29.667513],
       [29.669336],
       [29.671732],
       [29.671768],
       [29.65682 ],
       [29.665178],
       [29.669022],
       [29.673319],
       [29.661787],
       [29.669847],
       [29.673288],
       [29.675777],
       [29.6659  ],
       [29.640055],
       [29.638966],
       [29.6381  ],
       [29.64818 ],
       [29.647192],
       [29.649359],
       [29.661274],
       [29.647007],
       [29.651575],
       [29.627579],
       [29.665388],
       [29.672888],
       [29.668097],
       [29.645985],
       [29.657202],
       [29.648611],
       [29.656752],
       [29.668505],
       [29.67161 ],
       [29.67077 ],
       [29.672745],
       [29.672709],
       [29.673307],
       [29.666933],
       [29.661688],
       [29.635826],
       [29.660288],
       [29.671246],
       [29.670094],
       [29.664793],
       [29.650469],
       [29.650686],
       [29.634014],
       [29.660606],
       [29.659529],
       [29.668226],
       [29.672884],
       [29.672838],
       [29.664728],
       [29.671429],
       [29.667244],
       [29.668135],
       [29.659616],
       [29.659569],
       [29.670698],
       [29.67216 ],
       [29.671438],
       [29.674578],
       [29.617414],
       [29.614443],
       [29.652721],
       [29.662607],
       [29.650099],
       [29.665537],
       [29.671194],
       [29.673246],
       [29.673807],
       [29.6738  ],
       [29.674562],
       [29.674665],
       [29.660658],
       [29.651503],
       [29.663225],
       [29.670683],
       [29.673103],
       [29.675228],
       [29.67519 ],
       [29.675318],
       [29.664742],
       [29.629126],
       [29.652693],
       [29.67293 ],
       [29.674646],
       [29.67402 ],
       [29.645126],
       [29.65903 ],
       [29.667921],
       [29.645412],
       [29.640745],
       [29.660875],
       [29.66442 ],
       [29.640646],
       [29.640816],
       [29.650381],
       [29.662882],
       [29.667675],
       [29.670774],
       [29.671217],
       [29.6664  ],
       [29.661201],
       [29.654781],
       [29.667446],
       [29.669447],
       [29.673859],
       [29.65735 ],
       [29.671215],
       [29.672739],
       [29.67536 ],
       [29.677124],
       [29.669312],
       [29.669548],
       [29.669981],
       [29.67317 ],
       [29.670122],
       [29.672926],
       [29.675018],
       [29.667639],
       [29.66548 ],
       [29.66911 ],
       [29.670849],
       [29.67382 ],
       [29.674658],
       [29.664253],
       [29.665245],
       [29.673738],
       [29.673872],
       [29.674028],
       [29.67242 ],
       [29.666487],
       [29.65959 ],
       [29.671453],
       [29.673935],
       [29.676146],
       [29.67359 ],
       [29.674906],
       [29.672873],
       [29.669277],
       [29.666445],
       [29.637512],
       [29.669764],
       [29.666386],
       [29.670425],
       [29.674541],
       [29.675982],
       [29.674608],
       [29.67545 ],
       [29.672522],
       [29.674955],
       [29.67291 ],
       [29.6737  ],
       [29.672832],
       [29.669233],
       [29.671385],
       [29.668587],
       [29.673822],
       [29.673319],
       [29.672462],
       [29.670252],
       [29.667353]], dtype=float32)

In [198]:
model_2 = Sequential()

#add rnn layer
model_2.add(LSTM(64, input_shape=(5,32), return_sequences=True))
model_2.add(LSTM(16, return_sequences=False))
          
model_2.add(Dense(16, activation= 'relu'))
model_2.add(Dropout(.1))
model_2.add(Dense(8, activation= 'relu'))
model_2.add(Dropout(.2))
model_2.add(Dense(1))

model_2.compile(optimizer='adam', loss= 'mse', metrics= ['mae'])

history=model_2.fit(train_seq, epochs=20, validation_data= test_seq, verbose=1)

Epoch 1/20
6/6 [==============================] - 4s 149ms/step - loss: 1112.4305 - mae: 31.3881 - val_loss: 1019.0093 - val_mae: 28.9868
Epoch 2/20
6/6 [==============================] - 0s 23ms/step - loss: 1107.0321 - mae: 31.2998 - val_loss: 1010.9711 - val_mae: 28.8726
Epoch 3/20
6/6 [==============================] - 0s 18ms/step - loss: 1095.4514 - mae: 31.1265 - val_loss: 999.9990 - val_mae: 28.7176
Epoch 4/20
6/6 [==============================] - 0s 18ms/step - loss: 1082.9893 - mae: 30.9318 - val_loss: 983.7681 - val_mae: 28.4858
Epoch 5/20
6/6 [==============================] - 0s 18ms/step - loss: 1060.9448 - mae: 30.5849 - val_loss: 959.6238 - val_mae: 28.1353
Epoch 6/20
6/6 [==============================] - 0s 18ms/step - loss: 1033.9240 - mae: 30.1517 - val_loss: 923.0335 - val_mae: 27.5919
Epoch 7/20
6/6 [==============================] - 0s 16ms/step - loss: 990.6865 - mae: 29.4204 - val_loss: 869.4944 - val_mae: 26.7709
Epoch 8/20
6/6 [==============================] - 0s 18ms/step - loss: 921.1678 - mae: 28.2317 - val_loss: 800.0027 - val_mae: 25.6468
Epoch 9/20
6/6 [==============================] - 0s 15ms/step - loss: 859.5836 - mae: 27.1219 - val_loss: 723.6749 - val_mae: 24.3397
Epoch 10/20
6/6 [==============================] - 0s 16ms/step - loss: 756.7076 - mae: 25.2151 - val_loss: 651.7038 - val_mae: 23.0194
Epoch 11/20
6/6 [==============================] - 0s 15ms/step - loss: 687.6656 - mae: 23.7749 - val_loss: 590.4814 - val_mae: 21.8179
Epoch 12/20
6/6 [==============================] - 0s 16ms/step - loss: 620.5051 - mae: 22.4934 - val_loss: 538.0194 - val_mae: 20.7464
Epoch 13/20
6/6 [==============================] - 0s 16ms/step - loss: 575.4012 - mae: 21.3383 - val_loss: 492.0357 - val_mae: 19.7820
Epoch 14/20
6/6 [==============================] - 0s 19ms/step - loss: 550.4478 - mae: 20.7392 - val_loss: 452.2850 - val_mae: 18.8901
Epoch 15/20
6/6 [==============================] - 0s 17ms/step - loss: 501.0273 - mae: 19.5902 - val_loss: 415.6351 - val_mae: 18.0260
Epoch 16/20
6/6 [==============================] - 0s 16ms/step - loss: 440.4251 - mae: 18.0632 - val_loss: 381.2965 - val_mae: 17.1527
Epoch 17/20
6/6 [==============================] - 0s 16ms/step - loss: 405.8484 - mae: 17.4315 - val_loss: 349.5593 - val_mae: 16.3229
Epoch 18/20
6/6 [==============================] - 0s 15ms/step - loss: 388.1990 - mae: 16.6005 - val_loss: 320.4195 - val_mae: 15.5264
Epoch 19/20
6/6 [==============================] - 0s 15ms/step - loss: 357.3495 - mae: 15.7701 - val_loss: 294.2901 - val_mae: 14.7783
Epoch 20/20
6/6 [==============================] - 0s 15ms/step - loss: 317.3830 - mae: 14.6717 - val_loss: 271.4495 - val_mae: 14.0688